import { itemRequest, itemUpdateID, itemUpdatePacket } from "../shared/Messages"

export function itemCreator() {
    let shown = false
    let info = new itemUpdatePacket();
    let boxArr = []
    let mframe = CreateFrame("Frame", "torghastChoices", UIParent);
    mframe.SetWidth(1410);
    mframe.SetHeight(830);
    mframe.SetPoint("CENTER", 0, 0);
    mframe.SetBackdrop({
        bgFile: "Interface/TutorialFrame/TutorialFrameBackground",
        edgeFile: "Interface/DialogFrame/UI-DialogBox-Border",
        tile: true,
        tileSize: 20,
        edgeSize: 20,
        insets: { left: 2, right: 2, top: 2, bottom: 2 },
    });
    mframe.SetBackdropColor(0, 0, 0, 1);
    mframe.Hide();
    mframe.EnableMouse(true);
    mframe.RegisterForDrag("LeftButton");
    mframe.SetMovable(true);
    mframe.SetScript("OnDragStart", (self) => {
        self.StartMoving();
    });
    mframe.SetScript("OnDragStop", (self) => {
        self.StopMovingOrSizing();
    });

    let showBtn = CreateFrame("Button", "show", UIParent)
    showBtn.SetWidth(22)
    showBtn.SetHeight(22)
    showBtn.SetPoint("TOPRIGHT", -5, -105)
    let showTex = showBtn.CreateTexture("", "BACKGROUND")
    showTex.SetTexture("Interface\\BUTTONS\\UI-GroupLoot-Dice-Up.blp")
    showTex.SetAllPoints(showBtn)
    showBtn.HookScript("OnClick", (frame, evName, btnDown) => {
        if (shown) {
            mframe.Hide()
        } else {
            mframe.Show()
            clearInfo()
        }
    })

    let exitButn = CreateFrame("Button", "", mframe)
    exitButn.SetPoint("TOPRIGHT", mframe, "TOPRIGHT")
    exitButn.SetWidth(50)
    exitButn.SetHeight(50)
    let exittex = exitButn.CreateTexture("", "BACKGROUND")
    exittex.SetTexture("Interface\\BUTTONS\\UI-Panel-MinimizeButton-Up.blp")
    exittex.SetAllPoints(exitButn)
    exittex.SetPoint("CENTER", 0, 0)
    exitButn.HookScript("OnClick", (frame, evName, btnDown) => {
        shown = false
        mframe.Hide()
    })

    let clearInfoButton = CreateFrame("Button", 'clear', mframe);
    clearInfoButton.SetSize(200, 45);
    clearInfoButton.SetPoint("BOTTOMRIGHT", mframe, "BOTTOMRIGHT", -40, 55);
    clearInfoButton.SetNormalTexture("Interface\\BUTTONS\\UI-Panel-Button-Up");
    let choiceButtonText = clearInfoButton.CreateFontString("", "OVERLAY", "GameFontNormalLarge");
    choiceButtonText.SetText("Clear");
    choiceButtonText.SetPoint("LEFT", clearInfoButton, "LEFT", 40, 10);
    clearInfoButton.HookScript("OnClick", (frame, button, down) => {
        clearInfo()
    });


    let requestInfoButton = CreateFrame("Button", 'request', mframe);
    requestInfoButton.SetSize(clearInfoButton.GetWidth(), clearInfoButton.GetHeight());
    requestInfoButton.SetPoint("TOP", clearInfoButton, "BOTTOM", 0, 15);
    requestInfoButton.SetNormalTexture("Interface\\BUTTONS\\UI-Panel-Button-Up");
    let requestInfoButtonText = requestInfoButton.CreateFontString("", "OVERLAY", "GameFontNormalLarge");
    requestInfoButtonText.SetPoint("LEFT", requestInfoButton, "LEFT", 30, 10);
    requestInfoButtonText.SetText("Request");
    requestInfoButton.HookScript("OnClick", (frame, button, down) => {
        requestInfo()
    });

    let sendInfoButton = CreateFrame("Button", 'send', mframe);
    sendInfoButton.SetSize(clearInfoButton.GetWidth(), clearInfoButton.GetHeight());
    sendInfoButton.SetPoint("TOP", requestInfoButton, "BOTTOM", 0, 15);
    sendInfoButton.SetNormalTexture("Interface\\BUTTONS\\UI-Panel-Button-Up");
    let sendInfoButtonText = sendInfoButton.CreateFontString("", "OVERLAY", "GameFontNormalLarge");
    sendInfoButtonText.SetPoint("LEFT", sendInfoButton, "LEFT", 40, 10);
    sendInfoButtonText.SetText("Send");
    sendInfoButton.HookScript("OnClick", (frame, button, down) => {
        sendInfo()
    });

    createTextBoxes()

    OnCustomPacket(itemUpdateID, (packet) => {
        info.read(packet);
        updateUI()
    });

    function requestInfo() {
        let pkt = new itemRequest(info.entry)
        pkt.write().Send()
    }

    function clearInfo() {
        info = new itemUpdatePacket()
        updateUI()
    }

    function createTextBoxes() {
        boxArr[0] = createTextBoxAndText('Entry: ', 0, 0)
        boxArr[1] = createTextBoxAndText('Class: ', 0, 1)
        boxArr[2] = createTextBoxAndText('Subclass: ', 0, 2)
        boxArr[3] = createTextBoxAndText('SoundID: ', 0, 3)
        boxArr[4] = createTextBoxAndText('Name: ', 0, 4)
        boxArr[5] = createTextBoxAndText('DisplayID: ', 0, 5)
        boxArr[6] = createTextBoxAndText('Quality: ', 0, 6)
        boxArr[7] = createTextBoxAndText('Flags: ', 0, 7)
        boxArr[8] = createTextBoxAndText('Flags2: ', 0, 8)
        boxArr[9] = createTextBoxAndText('BuyCount: ', 0, 9)
        boxArr[10] = createTextBoxAndText('BuyPrice: ', 0, 10)
        boxArr[11] = createTextBoxAndText('SellPrice: ', 0, 11)
        boxArr[12] = createTextBoxAndText('InvType: ', 0, 12)
        boxArr[13] = createTextBoxAndText('AllowClass: ', 0, 13)
        boxArr[14] = createTextBoxAndText('AllowRace: ', 0, 14)
        boxArr[15] = createTextBoxAndText('ItemLevel: ', 0, 15)
        boxArr[16] = createTextBoxAndText('ReqLevel: ', 0, 16)
        boxArr[17] = createTextBoxAndText('ReqSkill: ', 0, 17)
        boxArr[18] = createTextBoxAndText('ReqSkillRank: ', 0, 18)
        boxArr[19] = createTextBoxAndText('ReqSpel: ', 0, 19)
        boxArr[20] = createTextBoxAndText('ReqHonorRank: ', 0, 20)
        boxArr[21] = createTextBoxAndText('ReqCityRank: ', 0, 21)
        boxArr[22] = createTextBoxAndText('ReqRepFaction: ', 0, 22)
        boxArr[23] = createTextBoxAndText('ReqRepRank: ', 0, 23)
        boxArr[24] = createTextBoxAndText('MaxCount: ', 0, 24)
        boxArr[25] = createTextBoxAndText('Stackable: ', 0, 25)
        boxArr[26] = createTextBoxAndText('ContainerSlots: ', 0, 26)
        boxArr[27] = createTextBoxAndText('StatsCount: ', 1, 0)
        boxArr[28] = createTextBoxAndText('StatType1: ', 1, 1)
        boxArr[29] = createTextBoxAndText('StatValue1: ', 1, 2)
        boxArr[30] = createTextBoxAndText('StatType2: ', 1, 3)
        boxArr[31] = createTextBoxAndText('StatValue2: ', 1, 4)
        boxArr[32] = createTextBoxAndText('StatType3: ', 1, 5)
        boxArr[33] = createTextBoxAndText('StatValue3: ', 1, 6)
        boxArr[34] = createTextBoxAndText('StatType4: ', 1, 7)
        boxArr[35] = createTextBoxAndText('StatValue4: ', 1, 8)
        boxArr[36] = createTextBoxAndText('StatType5: ', 1, 9)
        boxArr[37] = createTextBoxAndText('StatValue5: ', 1, 10)
        boxArr[38] = createTextBoxAndText('StatType6: ', 1, 11)
        boxArr[39] = createTextBoxAndText('StatValue6: ', 1, 12)
        boxArr[40] = createTextBoxAndText('StatType7: ', 1, 13)
        boxArr[41] = createTextBoxAndText('StatValue7: ', 1, 14)
        boxArr[42] = createTextBoxAndText('StatType8: ', 1, 15)
        boxArr[43] = createTextBoxAndText('StatValue8: ', 1, 16)
        boxArr[44] = createTextBoxAndText('StatType9: ', 1, 17)
        boxArr[45] = createTextBoxAndText('StatValue9: ', 1, 18)
        boxArr[46] = createTextBoxAndText('StatType10: ', 1, 19)
        boxArr[47] = createTextBoxAndText('StatValue10: ', 1, 20)
        boxArr[48] = createTextBoxAndText('ScalingStatDist: ', 1, 21)
        boxArr[49] = createTextBoxAndText('ScalingStatValue: ', 1, 22)
        boxArr[50] = createTextBoxAndText('DmgMinA: ', 1, 23)
        boxArr[51] = createTextBoxAndText('DmgMaxA: ', 1, 24)
        boxArr[52] = createTextBoxAndText('DmgTypeA: ', 1, 25)
        boxArr[53] = createTextBoxAndText('DmgMinB: ', 1, 26)
        boxArr[54] = createTextBoxAndText('DmgMaxb: ', 2, 0)
        boxArr[55] = createTextBoxAndText('DmgTypeB: ', 2, 1)
        boxArr[56] = createTextBoxAndText('Armor: ', 2, 2)
        boxArr[57] = createTextBoxAndText('HRes: ', 2, 3)
        boxArr[58] = createTextBoxAndText('FiRes: ', 2, 4)
        boxArr[59] = createTextBoxAndText('NRes: ', 2, 5)
        boxArr[60] = createTextBoxAndText('FrRes: ', 2, 6)
        boxArr[61] = createTextBoxAndText('SRes: ', 2, 7)
        boxArr[62] = createTextBoxAndText('ARes: ', 2, 8)
        boxArr[63] = createTextBoxAndText('Delay: ', 2, 9)
        boxArr[64] = createTextBoxAndText('Ammotype: ', 2, 10)
        boxArr[65] = createTextBoxAndText('ModRange: ', 2, 11)
        boxArr[66] = createTextBoxAndText('SpellID1: ', 2, 12)
        boxArr[67] = createTextBoxAndText('SpellTrigger1: ', 2, 13)
        boxArr[68] = createTextBoxAndText('SpellCharges1: ', 2, 14)
        boxArr[69] = createTextBoxAndText('SpellPPMRate1: ', 2, 15)
        boxArr[70] = createTextBoxAndText('SpellCooldown1: ', 2, 16)
        boxArr[71] = createTextBoxAndText('SpellCategory1: ', 2, 17)
        boxArr[72] = createTextBoxAndText('SpellCatCool1: ', 2, 18)
        boxArr[73] = createTextBoxAndText('SpellID2: ', 2, 19)
        boxArr[74] = createTextBoxAndText('SpellTrigger2: ', 2, 20)
        boxArr[75] = createTextBoxAndText('SpellCharges2: ', 2, 21)
        boxArr[76] = createTextBoxAndText('SpellPPMRate2: ', 2, 22)
        boxArr[77] = createTextBoxAndText('SpellCooldown2: ', 2, 23)
        boxArr[78] = createTextBoxAndText('SpellCategory2: ', 2, 24)
        boxArr[79] = createTextBoxAndText('SpellCatCool2: ', 2, 25)
        boxArr[80] = createTextBoxAndText('SpellID3: ', 2, 26)
        boxArr[81] = createTextBoxAndText('SpellTrigger3: ', 3, 0)
        boxArr[82] = createTextBoxAndText('SpellCharges3: ', 3, 1)
        boxArr[83] = createTextBoxAndText('SpellPPMRate3: ', 3, 2)
        boxArr[84] = createTextBoxAndText('SpellCooldown3: ', 3, 3)
        boxArr[85] = createTextBoxAndText('SpellCategory3: ', 3, 4)
        boxArr[86] = createTextBoxAndText('SpellCatCool3: ', 3, 5)
        boxArr[87] = createTextBoxAndText('SpellID4: ', 3, 6)
        boxArr[88] = createTextBoxAndText('SpellTrigger4: ', 3, 7)
        boxArr[89] = createTextBoxAndText('SpellCharges4: ', 3, 8)
        boxArr[90] = createTextBoxAndText('SpellPPMRate4: ', 3, 9)
        boxArr[91] = createTextBoxAndText('SpellCooldown4: ', 3, 10)
        boxArr[92] = createTextBoxAndText('SpellCategory4: ', 3, 11)
        boxArr[93] = createTextBoxAndText('SpellCatCool4: ', 3, 12)
        boxArr[94] = createTextBoxAndText('SpellID5: ', 3, 13)
        boxArr[95] = createTextBoxAndText('SpellTrigger5: ', 3, 14)
        boxArr[96] = createTextBoxAndText('SpellCharges5: ', 3, 15)
        boxArr[97] = createTextBoxAndText('SpellPPMRate5: ', 3, 16)
        boxArr[98] = createTextBoxAndText('SpellCooldown5: ', 3, 17)
        boxArr[99] = createTextBoxAndText('SpellCategory5: ', 3, 18)
        boxArr[100] = createTextBoxAndText('SpellCatCool5: ', 3, 19)
        boxArr[101] = createTextBoxAndText('Bonding: ', 3, 20)
        boxArr[102] = createTextBoxAndText('Description: ', 3, 21)
        boxArr[103] = createTextBoxAndText('PageText: ', 3, 22)
        boxArr[104] = createTextBoxAndText('LanguageID: ', 3, 23)
        boxArr[105] = createTextBoxAndText('PageMaterial: ', 3, 24)
        boxArr[106] = createTextBoxAndText('StartQuest: ', 3, 25)
        boxArr[107] = createTextBoxAndText('LockID: ', 3, 26)
        boxArr[108] = createTextBoxAndText('Material: ', 4, 0)
        boxArr[109] = createTextBoxAndText('Sheath: ', 4, 1)
        boxArr[110] = createTextBoxAndText('RandProp: ', 4, 2)
        boxArr[111] = createTextBoxAndText('RandSuff: ', 4, 3)
        boxArr[112] = createTextBoxAndText('Block: ', 4, 4)
        boxArr[113] = createTextBoxAndText('ItemSet: ', 4, 5)
        boxArr[114] = createTextBoxAndText('MaxDurability: ', 4, 6)
        boxArr[115] = createTextBoxAndText('Area: ', 4, 7)
        boxArr[116] = createTextBoxAndText('Map: ', 4, 8)
        boxArr[117] = createTextBoxAndText('BagFam: ', 4, 9)
        boxArr[118] = createTextBoxAndText('TotemCat: ', 4, 10)
        boxArr[119] = createTextBoxAndText('SocketBonus: ', 4, 11)
        boxArr[120] = createTextBoxAndText('GemProp: ', 4, 12)
        boxArr[121] = createTextBoxAndText('ReqDisSkill: ', 4, 13)
        boxArr[122] = createTextBoxAndText('ArmorDmgMod: ', 4, 14)
        boxArr[123] = createTextBoxAndText('Duration: ', 4, 15)
        boxArr[124] = createTextBoxAndText('ItemLimitCat: ', 4, 16)
        boxArr[125] = createTextBoxAndText('HolidayID: ', 4, 17)
        boxArr[126] = createTextBoxAndText('ScriptID: ', 4, 18)
        boxArr[127] = createTextBoxAndText('DisID: ', 4, 19)
        boxArr[128] = createTextBoxAndText('FoodType: ', 4, 20)
        boxArr[129] = createTextBoxAndText('MinMoneyLoot: ', 4, 21)
        boxArr[130] = createTextBoxAndText('MaxMoneyLoot: ', 4, 22)
        boxArr[131] = createTextBoxAndText('FlagsCu: ', 4, 23)
    }

    function updateUI() {
        boxArr[0].SetText(info.entry.toString())
        boxArr[1].SetText(info.iclass.toString())
        boxArr[2].SetText(info.subclass.toString())
        boxArr[3].SetText(info.soundOverrideSubclass.toString())
        boxArr[4].SetText(info.name)
        boxArr[5].SetText(info.displayID.toString())
        boxArr[6].SetText(info.quality.toString())
        boxArr[7].SetText(info.flags.toString())
        boxArr[8].SetText(info.flags2.toString())
        boxArr[9].SetText(info.buyCount.toString())
        boxArr[10].SetText(info.buyPrice.toString())
        boxArr[11].SetText(info.sellPrice.toString())
        boxArr[12].SetText(info.invType.toString())
        boxArr[13].SetText(info.allowClass.toString())
        boxArr[14].SetText(info.allowRace.toString())
        boxArr[15].SetText(info.itemLevel.toString())
        boxArr[16].SetText(info.reqLevel.toString())
        boxArr[17].SetText(info.reqSkill.toString())
        boxArr[18].SetText(info.reqSkillRank.toString())
        boxArr[19].SetText(info.reqSpel.toString())
        boxArr[20].SetText(info.reqHonorRank.toString())
        boxArr[21].SetText(info.reqCityRank.toString())
        boxArr[22].SetText(info.reqRepFaction.toString())
        boxArr[23].SetText(info.reqRepRank.toString())
        boxArr[24].SetText(info.maxCount.toString())
        boxArr[25].SetText(info.stackable.toString())
        boxArr[26].SetText(info.containerSlots.toString())
        boxArr[27].SetText(info.statsCount.toString())
        boxArr[28].SetText(info.statType1.toString())
        boxArr[29].SetText(info.statValue1.toString())
        boxArr[30].SetText(info.statType2.toString())
        boxArr[31].SetText(info.statValue2.toString())
        boxArr[32].SetText(info.statType3.toString())
        boxArr[33].SetText(info.statValue3.toString())
        boxArr[34].SetText(info.statType4.toString())
        boxArr[35].SetText(info.statValue4.toString())
        boxArr[36].SetText(info.statType5.toString())
        boxArr[37].SetText(info.statValue5.toString())
        boxArr[38].SetText(info.statType6.toString())
        boxArr[39].SetText(info.statValue6.toString())
        boxArr[40].SetText(info.statType7.toString())
        boxArr[41].SetText(info.statValue7.toString())
        boxArr[42].SetText(info.statType8.toString())
        boxArr[43].SetText(info.statValue8.toString())
        boxArr[44].SetText(info.statType9.toString())
        boxArr[45].SetText(info.statValue9.toString())
        boxArr[46].SetText(info.statType10.toString())
        boxArr[47].SetText(info.statValue10.toString())
        boxArr[48].SetText(info.scalingStatDist.toString())
        boxArr[49].SetText(info.scalingStatValue.toString())
        boxArr[50].SetText(info.dmgMinA.toString())
        boxArr[51].SetText(info.dmgMaxA.toString())
        boxArr[52].SetText(info.dmgTypeA.toString())
        boxArr[53].SetText(info.dmgMinB.toString())
        boxArr[54].SetText(info.dmgMaxb.toString())
        boxArr[55].SetText(info.dmgTypeB.toString())
        boxArr[56].SetText(info.armor.toString())
        boxArr[57].SetText(info.hRes.toString())
        boxArr[58].SetText(info.fiRes.toString())
        boxArr[59].SetText(info.nRes.toString())
        boxArr[60].SetText(info.frRes.toString())
        boxArr[61].SetText(info.sRes.toString())
        boxArr[62].SetText(info.aRes.toString())
        boxArr[63].SetText(info.delay.toString())
        boxArr[64].SetText(info.ammotype.toString())
        boxArr[65].SetText(info.rangedModRange.toString())
        boxArr[66].SetText(info.spellID1.toString())
        boxArr[67].SetText(info.SpellTrigger1.toString())
        boxArr[68].SetText(info.SpellCharges1.toString())
        boxArr[69].SetText(info.SpellPPMRate1.toString())
        boxArr[70].SetText(info.SpellCooldown1.toString())
        boxArr[71].SetText(info.SpellCategory1.toString())
        boxArr[72].SetText(info.SpellCategoryCooldown1.toString())
        boxArr[73].SetText(info.spellID2.toString())
        boxArr[74].SetText(info.SpellTrigger2.toString())
        boxArr[75].SetText(info.SpellCharges2.toString())
        boxArr[76].SetText(info.SpellPPMRate2.toString())
        boxArr[77].SetText(info.SpellCooldown2.toString())
        boxArr[78].SetText(info.SpellCategory2.toString())
        boxArr[79].SetText(info.SpellCategoryCooldown2.toString())
        boxArr[80].SetText(info.spellID3.toString())
        boxArr[81].SetText(info.SpellTrigger3.toString())
        boxArr[82].SetText(info.SpellCharges3.toString())
        boxArr[83].SetText(info.SpellPPMRate3.toString())
        boxArr[84].SetText(info.SpellCooldown3.toString())
        boxArr[85].SetText(info.SpellCategory3.toString())
        boxArr[86].SetText(info.SpellCategoryCooldown3.toString())
        boxArr[87].SetText(info.spellID4.toString())
        boxArr[88].SetText(info.SpellTrigger4.toString())
        boxArr[89].SetText(info.SpellCharges4.toString())
        boxArr[90].SetText(info.SpellPPMRate4.toString())
        boxArr[91].SetText(info.SpellCooldown4.toString())
        boxArr[92].SetText(info.SpellCategory4.toString())
        boxArr[93].SetText(info.SpellCategoryCooldown4.toString())
        boxArr[94].SetText(info.spellID5.toString())
        boxArr[95].SetText(info.SpellTrigger5.toString())
        boxArr[96].SetText(info.SpellCharges5.toString())
        boxArr[97].SetText(info.SpellPPMRate5.toString())
        boxArr[98].SetText(info.SpellCooldown5.toString())
        boxArr[99].SetText(info.SpellCategory5.toString())
        boxArr[100].SetText(info.SpellCategoryCooldown5.toString())
        boxArr[101].SetText(info.bonding.toString())
        boxArr[102].SetText(info.description)
        boxArr[103].SetText(info.pageText.toString())
        boxArr[104].SetText(info.languageID.toString())
        boxArr[105].SetText(info.pageMaterial.toString())
        boxArr[106].SetText(info.startQuest.toString())
        boxArr[107].SetText(info.lockID.toString())
        boxArr[108].SetText(info.material.toString())
        boxArr[109].SetText(info.sheath.toString())
        boxArr[110].SetText(info.randProp.toString())
        boxArr[111].SetText(info.randSuff.toString())
        boxArr[112].SetText(info.block.toString())
        boxArr[113].SetText(info.itemSet.toString())
        boxArr[114].SetText(info.maxDurability.toString())
        boxArr[115].SetText(info.area.toString())
        boxArr[116].SetText(info.map.toString())
        boxArr[117].SetText(info.bagFam.toString())
        boxArr[118].SetText(info.totemCat.toString())
        boxArr[119].SetText(info.socketBonus.toString())
        boxArr[120].SetText(info.gemProp.toString())
        boxArr[121].SetText(info.reqDisSkill.toString())
        boxArr[122].SetText(info.armorDmgMod.toString())
        boxArr[123].SetText(info.duration.toString())
        boxArr[124].SetText(info.itemLimitCat.toString())
        boxArr[125].SetText(info.holidayID.toString())
        boxArr[126].SetText(info.scriptID.toString())
        boxArr[127].SetText(info.disID.toString())
        boxArr[128].SetText(info.foodType.toString())
        boxArr[129].SetText(info.minMoneyLoot.toString())
        boxArr[130].SetText(info.maxMoneyLoot.toString())
        boxArr[131].SetText(info.flagsCu.toString())

    }

    function sendInfo() {
        info.entry = Number(boxArr[0].GetText())
        info.iclass = Number(boxArr[1].GetText())
        info.subclass = Number(boxArr[2].GetText())
        info.soundOverrideSubclass = Number(boxArr[3].GetText())
        info.name = boxArr[4].GetText()
        info.displayID = Number(boxArr[5].GetText())
        info.quality = Number(boxArr[6].GetText())
        info.flags = Number(boxArr[7].GetText())
        info.flags2 = Number(boxArr[8].GetText())
        info.buyCount = Number(boxArr[9].GetText())
        info.buyPrice = Number(boxArr[10].GetText())
        info.sellPrice = Number(boxArr[11].GetText())
        info.invType = Number(boxArr[12].GetText())
        info.allowClass = Number(boxArr[13].GetText())
        info.allowRace = Number(boxArr[14].GetText())
        info.itemLevel = Number(boxArr[15].GetText())
        info.reqLevel = Number(boxArr[16].GetText())
        info.reqSkill = Number(boxArr[17].GetText())
        info.reqSkillRank = Number(boxArr[18].GetText())
        info.reqSpel = Number(boxArr[19].GetText())
        info.reqHonorRank = Number(boxArr[20].GetText())
        info.reqCityRank = Number(boxArr[21].GetText())
        info.reqRepFaction = Number(boxArr[22].GetText())
        info.reqRepRank = Number(boxArr[23].GetText())
        info.maxCount = Number(boxArr[24].GetText())
        info.stackable = Number(boxArr[25].GetText())
        info.containerSlots = Number(boxArr[26].GetText())
        info.statsCount = Number(boxArr[27].GetText())
        info.statType1 = Number(boxArr[28].GetText())
        info.statValue1 = Number(boxArr[29].GetText())
        info.statType2 = Number(boxArr[30].GetText())
        info.statValue2 = Number(boxArr[31].GetText())
        info.statType3 = Number(boxArr[32].GetText())
        info.statValue3 = Number(boxArr[33].GetText())
        info.statType4 = Number(boxArr[34].GetText())
        info.statValue4 = Number(boxArr[35].GetText())
        info.statType5 = Number(boxArr[36].GetText())
        info.statValue5 = Number(boxArr[37].GetText())
        info.statType6 = Number(boxArr[38].GetText())
        info.statValue6 = Number(boxArr[39].GetText())
        info.statType7 = Number(boxArr[40].GetText())
        info.statValue7 = Number(boxArr[41].GetText())
        info.statType8 = Number(boxArr[42].GetText())
        info.statValue8 = Number(boxArr[43].GetText())
        info.statType9 = Number(boxArr[44].GetText())
        info.statValue9 = Number(boxArr[45].GetText())
        info.statType10 = Number(boxArr[46].GetText())
        info.statValue10 = Number(boxArr[47].GetText())
        info.scalingStatDist = Number(boxArr[48].GetText())
        info.scalingStatValue = Number(boxArr[49].GetText())
        info.dmgMinA = Number(boxArr[50].GetText())
        info.dmgMaxA = Number(boxArr[51].GetText())
        info.dmgTypeA = Number(boxArr[52].GetText())
        info.dmgMinB = Number(boxArr[53].GetText())
        info.dmgMaxb = Number(boxArr[54].GetText())
        info.dmgTypeB = Number(boxArr[55].GetText())
        info.armor = Number(boxArr[56].GetText())
        info.hRes = Number(boxArr[57].GetText())
        info.fiRes = Number(boxArr[58].GetText())
        info.nRes = Number(boxArr[59].GetText())
        info.frRes = Number(boxArr[60].GetText())
        info.sRes = Number(boxArr[61].GetText())
        info.aRes = Number(boxArr[62].GetText())
        info.delay = Number(boxArr[63].GetText())
        info.ammotype = Number(boxArr[64].GetText())
        info.rangedModRange = Number(boxArr[65].GetText())
        info.spellID1 = Number(boxArr[66].GetText())
        info.SpellTrigger1 = Number(boxArr[67].GetText())
        info.SpellCharges1 = Number(boxArr[68].GetText())
        info.SpellPPMRate1 = Number(boxArr[69].GetText())
        info.SpellCooldown1 = Number(boxArr[70].GetText())
        info.SpellCategory1 = Number(boxArr[71].GetText())
        info.SpellCategoryCooldown1 = Number(boxArr[72].GetText())
        info.spellID2 = Number(boxArr[73].GetText())
        info.SpellTrigger2 = Number(boxArr[74].GetText())
        info.SpellCharges2 = Number(boxArr[75].GetText())
        info.SpellPPMRate2 = Number(boxArr[76].GetText())
        info.SpellCooldown2 = Number(boxArr[77].GetText())
        info.SpellCategory2 = Number(boxArr[78].GetText())
        info.SpellCategoryCooldown2 = Number(boxArr[79].GetText())
        info.spellID3 = Number(boxArr[80].GetText())
        info.SpellTrigger3 = Number(boxArr[81].GetText())
        info.SpellCharges3 = Number(boxArr[82].GetText())
        info.SpellPPMRate3 = Number(boxArr[83].GetText())
        info.SpellCooldown3 = Number(boxArr[84].GetText())
        info.SpellCategory3 = Number(boxArr[85].GetText())
        info.SpellCategoryCooldown3 = Number(boxArr[86].GetText())
        info.spellID4 = Number(boxArr[87].GetText())
        info.SpellTrigger4 = Number(boxArr[88].GetText())
        info.SpellCharges4 = Number(boxArr[89].GetText())
        info.SpellPPMRate4 = Number(boxArr[90].GetText())
        info.SpellCooldown4 = Number(boxArr[91].GetText())
        info.SpellCategory4 = Number(boxArr[92].GetText())
        info.SpellCategoryCooldown4 = Number(boxArr[93].GetText())
        info.spellID5 = Number(boxArr[94].GetText())
        info.SpellTrigger5 = Number(boxArr[95].GetText())
        info.SpellCharges5 = Number(boxArr[96].GetText())
        info.SpellPPMRate5 = Number(boxArr[97].GetText())
        info.SpellCooldown5 = Number(boxArr[98].GetText())
        info.SpellCategory5 = Number(boxArr[99].GetText())
        info.SpellCategoryCooldown5 = Number(boxArr[100].GetText())
        info.bonding = Number(boxArr[101].GetText())
        info.description = boxArr[102].GetText()
        info.pageText = Number(boxArr[103].GetText())
        info.languageID = Number(boxArr[104].GetText())
        info.pageMaterial = Number(boxArr[105].GetText())
        info.startQuest = Number(boxArr[106].GetText())
        info.lockID = Number(boxArr[107].GetText())
        info.material = Number(boxArr[108].GetText())
        info.sheath = Number(boxArr[109].GetText())
        info.randProp = Number(boxArr[110].GetText())
        info.randSuff = Number(boxArr[111].GetText())
        info.block = Number(boxArr[112].GetText())
        info.itemSet = Number(boxArr[113].GetText())
        info.maxDurability = Number(boxArr[114].GetText())
        info.area = Number(boxArr[115].GetText())
        info.map = Number(boxArr[116].GetText())
        info.bagFam = Number(boxArr[117].GetText())
        info.totemCat = Number(boxArr[118].GetText())
        info.socketBonus = Number(boxArr[119].GetText())
        info.gemProp = Number(boxArr[120].GetText())
        info.reqDisSkill = Number(boxArr[121].GetText())
        info.armorDmgMod = Number(boxArr[122].GetText())
        info.duration = Number(boxArr[123].GetText())
        info.itemLimitCat = Number(boxArr[124].GetText())
        info.holidayID = Number(boxArr[125].GetText())
        info.scriptID = Number(boxArr[126].GetText())
        info.disID = Number(boxArr[127].GetText())
        info.foodType = Number(boxArr[128].GetText())
        info.minMoneyLoot = Number(boxArr[129].GetText())
        info.maxMoneyLoot = Number(boxArr[130].GetText())
        info.flagsCu = Number(boxArr[131].GetText())

        info.write().Send()
        clearInfo()
    }

    function createTextBoxAndText(name: string, x: number, y: number) {
        let textbox = CreateFrame('EditBox', name + 'editbox', mframe)
        textbox.SetSize(160, 30)
        textbox.SetFont("Fonts\\ARIALN.TTF", 14)
        textbox.SetMaxLetters(50)
        textbox.SetMultiLine(false)

        let text = textbox.CreateFontString('', "OVERLAY", 'GameTooltipText');
        text.SetPoint('TOPLEFT', mframe, 'TOPLEFT', (x * 280) + 10, (-y * 30) - 20)
        text.SetText(name)

        textbox.SetPoint('LEFT', text, 'RIGHT', 5, 0)

        let searchtexBox = textbox.CreateTexture("", "BACKGROUND")
        searchtexBox.SetTexture("Interface\\COMMON\\Common-Input-Border.blp")
        searchtexBox.SetPoint("CENTER", textbox, "CENTER", -5, -5)
        searchtexBox.SetSize(textbox.GetWidth(), textbox.GetHeight())

        return textbox
    }
}
