
export let statToName = CreateDictionary<uint32,TSString>({
    0: 'Mana',
    1: 'Health',
    3: 'Agility',
    4: 'Strength',
    5: 'Intellect',
    6: 'Spirit',
    7: 'Stamina',
    12: 'Defense Skill',
    13: 'Dodge',
    14: 'Parry',
    15: 'Block',
    16: 'Melee Hit',
    17: 'Ranged Hit',
    18: 'Spell Hit',
    19: 'Melee Critical',
    20: 'Ranged Critical',
    21: 'Spell Critical',
    22: 'Melee Hit Taken',
    23: 'Ranged Hit Taken',
    24: 'Spell Hit Taken',
    25: 'Melee Critical Taken',
    26: 'Ranged Critical Taken',
    27: 'Spell Critical Taken',
    28: 'Melee Haste',
    29: 'Ranged Haste',
    30: 'Spell Haste',
    31: 'Hit Rating',
    32: 'Critical Strike Rating',
    33: 'Hit Taken Rating',
    34: 'Critical Taken Rating',
    35: 'Resilience Rating',
    36: 'Haste',
    37: 'Expertise',
    38: 'Attack Power',
    39: 'Ranged Attack Power',
    40: 'Feral Attack Power',
    41: 'Spell Healing Power',
    42: 'Spell Damage Power',
    43: 'Mana Regen',
    44: 'Armor Penetration',
    45: 'Spell Penetration',
    46: 'Health Regen',
    47: 'Spell Penetration',
    48: 'Block Value',
})

const enum itemStats /**@realType:uint32*/ {
    MANA = 0,
    HEALTH = 1,
    AGILITY = 3,
    STRENGTH = 4,
    INTELLECT = 5,
    SPIRIT = 6,
    STAMINA = 7,
    DEFENSE_SKILL_RATING = 12,
    DODGE_RATING = 13,
    PARRY_RATING = 14,
    BLOCK_RATING = 15,
    HIT_MELEE_RATING = 16,
    HIT_RANGED_RATING = 17,
    HIT_SPELL_RATING = 18,
    CRIT_MELEE_RATING = 19,
    CRIT_RANGED_RATING = 20,
    CRIT_SPELL_RATING = 21,
    HIT_TAKEN_MELEE_RATING = 22,
    HIT_TAKEN_RANGED_RATING = 23,
    HIT_TAKEN_SPELL_RATING = 24,
    CRIT_TAKEN_MELEE_RATING = 25,
    CRIT_TAKEN_RANGED_RATING = 26,
    CRIT_TAKEN_SPELL_RATING = 27,
    HASTE_MELEE_RATING = 28,
    HASTE_RANGED_RATING = 29,
    HASTE_SPELL_RATING = 30,
    HIT_RATING = 31,
    CRIT_RATING = 32,
    HIT_TAKEN_RATING = 33,
    CRIT_TAKEN_RATING = 34,
    RESILIENCE_RATING = 35,
    HASTE_RATING = 36,
    EXPERTISE_RATING = 37,
    ATTACK_POWER = 38,
    RANGED_ATTACK_POWER = 39,
    SPELL_HEALING_DONE = 41,
    SPELL_DAMAGE_DONE = 42,
    MANA_REGENERATION = 43,
    ARMOR_PENETRATION_RATING = 44,
    SPELL_POWER = 45,
    HEALTH_REGEN = 46,
    SPELL_PENETRATION = 47,
    BLOCK_VALUE = 48,
}